<?php

define("GRUPONITS1", "SELECT nm_juridicas.numid,nm_juridicas.razon_social,nm_sucursal.telefono,nm_sucursal.direccion,nm_sucursal.ciudad,nm_sucursal.pais,np_ciudades.nom_ciudad FROM nm_juridicas,nm_sucursal,np_ciudades WHERE nm_juridicas.numid=nm_sucursal.numid and nm_sucursal.ciudad=np_ciudades.id_ciudad ");
define("GRUPONITS2","SELECT nm_juridicas.numid,nm_juridicas.razon_social,nm_juridicas.numid,nm_sucursal.telefono,nm_sucursal.direccion,nm_sucursal.ciudad,nm_sucursal.pais,np_ciudades.nom_ciudad FROM nm_juridicas,nm_sucursal,np_ciudades,nm_nits WHERE nm_juridicas.numid=nm_sucursal.numid and nm_sucursal.ciudad=np_ciudades.id_ciudad AND nm_juridicas.numid=nm_nits.numid ");
define("GRUPONITS3","select nm_juridicas.numid,nm_juridicas.razon_social from nm_juridicas,nm_nits where nm_juridicas.numid=nm_nits.numid ");
define("RETORNARCONTACTOS1","SELECT nm_nits.numid,nm_contactos.email,nm_contactos.id_contacto,nm_contactos.cc_contacto,nm_contactos.nom_contacto,nm_contactos.cargo,nm_contactos.tel_contacto,nm_sucursal.direccion,np_ciudades.nom_ciudad,np_deptos.nom_dpto,nm_contactos.estado,(SELECT concat(nm_personas.nombres,' ',nm_personas.apellidos) FROM nm_personas WHERE nm_personas.numid=nm_nits.numid) as personas,(SELECT nm_juridicas.razon_social FROM nm_juridicas WHERE nm_juridicas.numid=nm_nits.numid ) as juridicas FROM nm_contactos,nm_sucursal,nm_nits,np_paises,np_deptos,np_ciudades WHERE nm_nits.numid=nm_sucursal.numid AND nm_sucursal.id_sucursal=nm_contactos.id_sucursal AND np_paises.id_pais=np_deptos.id_pais AND np_deptos.id_dpto=np_ciudades.id_dpto AND nm_sucursal.ciudad=np_ciudades.id_ciudad ");
define("IM_ITEMS1","SELECT im_items.foto,im_items.nom_item,im_items.cod_item,im_items.iva,im_items.alter_item,UPPER(ip_grupos.nom_grupo) as nom_grupo,ip_grupos.cod_grupo,UPPER(ip_marcas.nom_marca) as nom_marca,ip_marcas.id_marca,im_items.precio_vta,UPPER(ip_tipos.descrip) as descrip,ip_tipos.id_tipo,UPPER(ip_modelos.descrip_modelo) as descrip_modelo,ip_modelos.id_modelo,UPPER(ip_dimen.nom_dimen) as nom_dimen,ip_dimen.id_dimen,UPPER(ip_unidades.nom_unidad) as nom_unidad,ip_unidades.cod_unidad,CAST((ir_salinve.saldo-im_items.minimo) as INT) AS saldoAlerta,CAST(ir_salinve.saldo AS INT) as saldo,im_items.maximo,im_items.minimo,UPPER(ip_dtbasicos.dt_basico) as estado FROM im_items,ip_grupos,ip_marcas,ip_tipos,ip_modelos,ip_dimen,ip_unidades,ir_salinve,ip_dtbasicos WHERE im_items.grup_item=ip_grupos.cod_grupo AND im_items.estado_item=ip_dtbasicos.sec_basico AND im_items.id_marca=ip_marcas.id_marca AND im_items.tipo_item=ip_tipos.id_tipo AND im_items.modelo=ip_modelos.id_modelo AND im_items.dimensiones=ip_dimen.id_dimen AND im_items.unidad=ip_unidades.cod_unidad AND im_items.cod_item=ir_salinve.cod_item AND ir_salinve.codbodeg=1 ");
define("IM_ITEMS2","SELECT * FROM im_items ");
define("IM_ITEMS3","SELECT im_items.foto,im_items.nom_item,im_items.cod_item,im_items.iva,im_items.alter_item,UPPER(ip_grupos.nom_grupo) as nom_grupo,ip_grupos.cod_grupo,UPPER(ip_marcas.nom_marca) as nom_marca,ip_marcas.id_marca,im_items.precio_vta,UPPER(ip_tipos.descrip) as descrip,ip_tipos.id_tipo,UPPER(ip_modelos.descrip_modelo) as descrip_modelo,ip_modelos.id_modelo,UPPER(ip_dimen.nom_dimen) as nom_dimen,ip_dimen.id_dimen,UPPER(ip_unidades.nom_unidad) as nom_unidad,ip_unidades.cod_unidad,im_items.maximo,im_items.minimo,UPPER(ip_dtbasicos.dt_basico) as estado FROM im_items,ip_grupos,ip_marcas,ip_tipos,ip_modelos,ip_dimen,ip_unidades,ip_dtbasicos WHERE im_items.grup_item=ip_grupos.cod_grupo AND im_items.estado_item=ip_dtbasicos.sec_basico AND im_items.id_marca=ip_marcas.id_marca AND im_items.tipo_item=ip_tipos.id_tipo AND im_items.modelo=ip_modelos.id_modelo AND im_items.dimensiones=ip_dimen.id_dimen AND im_items.unidad=ip_unidades.cod_unidad ");
define("SUCURSALES1","select nm_sucursal.id_region,nm_sucursal.id_sucursal,nm_sucursal.numid,nm_sucursal.orden,nm_sucursal.direccion,nm_sucursal.telefono,nm_sucursal.telefono2,nm_sucursal.fax,nm_sucursal.ciudad,nm_sucursal.pais,UPPER(nm_sucursal.nom_sucur) as nom_sucur,nm_sucursal.suc_lat_gps,nm_sucursal.suc_lng_gps,nm_sucursal.cod_clie_helisa,nm_sucursal.cod_prv_helisa,nm_sucursal.estado,np_ciudades.nom_ciudad,np_paises.nom_pais from nm_sucursal,np_ciudades,np_paises where nm_sucursal.ciudad=np_ciudades.id_ciudad and nm_sucursal.pais=np_paises.id_pais ");
define("DTBASICOS1","select ip_dtbasicos.id_basico,ip_dtbasicos.estado,UPPER(ip_dtbasicos.dt_basico) as dt_basico,ip_dtbasicos.sec_basico from ip_dtbasicos ");
define("VRREQUERIM1","select vr_requerim.cod_trans,IF(vr_requerim.asesor_asignd='','',UPPER(am_usuarios.nombre)) as nombre,vr_requerim.id_requerim,vr_requerim.fechora,vr_requerim.id_fuente,vr_requerim.nom_cliente,vr_requerim.suc_cliente,vr_requerim.id_contacto,vr_requerim.de_linea,vr_requerim.estado,UPPER(nm_sucursal.nom_sucur) as nom_sucur,np_ciudades.nom_ciudad,nm_contactos.nom_contacto,ip_lineas.descrip,UPPER(ip_dtbasicos.dt_basico) as textoFuente,(SELECT UPPER(dt_basico) FROM ip_dtbasicos WHERE sec_basico=vr_requerim.estado) as textoEstado from am_usuarios,vr_requerim,nm_sucursal,np_ciudades,nm_contactos,ip_lineas,ip_dtbasicos where vr_requerim.suc_cliente=nm_sucursal.id_sucursal and nm_sucursal.ciudad=np_ciudades.id_ciudad and vr_requerim.id_contacto=nm_contactos.id_contacto and vr_requerim.de_linea=ip_lineas.id_linea and vr_requerim.id_fuente=ip_dtbasicos.sec_basico and (vr_requerim.asesor_asignd=am_usuarios.codusr OR vr_requerim.asesor_asignd='')  ");
define("AMALERTAS1","select am_alertas.id_alerta,am_alertas.id_tipoalerta,am_alertas.id_proceso,am_alertas.fecha_ini,ap_tipoalerta.descrip_alert from am_alertas,ap_tipoalerta where am_alertas.id_tipoalerta=ap_tipoalerta.id_tipoalerta and am_alertas.id_estado=58 ");
define("IRSALINVE1","SELECT ir_salinve.cod_item,ir_salinve.codbodeg,CAST(ir_salinve.saldo AS INT) saldo,ir_salinve.numid,ir_salinve.costot_usd,ir_salinve.fecha_arribo,UPPER(im_bodeg.nom_bodega) as nom_bodega,(SELECT apelli_nom FROM nm_personas WHERE nm_personas.numid=ir_salinve.numid) as persona FROM ir_salinve,im_bodeg WHERE ir_salinve.codbodeg=im_bodeg.cod_bodega ");
define("IRRESINVE1","SELECT ir_resinve.cod_item,ir_resinve.codbodeg,ir_resinve.saldo,ir_resinve.numid,ir_resinve.fecha_arribo,UPPER(im_bodeg.nom_bodega) as nom_bodega,(SELECT apelli_nom FROM nm_personas WHERE nm_personas.numid=ir_resinve.numid) as persona FROM ir_resinve,im_bodeg WHERE ir_resinve.codbodeg=im_bodeg.cod_bodega ");
define("AMUSUARIOS1","SELECT am_usuarios.codusr,UPPER(am_usuarios.nombre) as nombre,am_usuarios.numid,am_usuarios.email,am_usuarios.paswd,am_usuarios.id_rol,am_usuarios.estado,am_usuarios.fec_graba,am_usuarios.foto FROM am_usuarios ");
define("NMEMPLEADOS1","SELECT nm_empleados.codemple,nm_empleados.usuario,nm_empleados.numid,nm_personas.apelli_nom FROM nm_empleados,nm_personas WHERE nm_empleados.numid=nm_personas.numid ");
define("NMPERSONAS1","SELECT nm_personas.apelli_nom,nm_personas.numid FROM nm_personas,nm_nits WHERE nm_personas.numid=nm_nits.numid AND (nm_nits.tipo_entidad=73 OR nm_nits.tipo_entidad=71 OR nm_nits.tipo_entidad=70) ");
define("IROPERACIONES1","SELECT ir_operaciones.id_operacion,DATE(ir_operaciones.fecha_registro) as fecha_registro,CONCAT(ir_operaciones.trans_base,' ',ir_operaciones.numero_trans) AS SIPV,CAST(ir_detalle_oper.cantidad AS SIGNED INTEGER) AS cantidad, CONCAT(im_items.cod_item,' - ',im_items.alter_item,' - ',im_items.nom_item) as nom_item,im_items.num_parte, ip_marcas.nom_marca,nm_sucursal.numid, (SELECT nm_juridicas.razon_social FROM nm_juridicas WHERE nm_juridicas.numid=nm_sucursal.numid ) as nm_juridicas, (SELECT np_ciudades.nom_ciudad FROM np_ciudades WHERE np_ciudades.id_ciudad=nm_sucursal.ciudad) as ciudad,UPPER(ip_modelos.descrip_modelo) AS descrip_modelo,ir_detalle_oper.id_detalle,UPPER(cp_tipo_importacion.nom_tipo) as nom_tipo FROM ir_operaciones,ir_detalle_oper,im_items,ip_marcas,nm_sucursal,ip_modelos,cp_tipo_importacion WHERE ir_operaciones.id_operacion=ir_detalle_oper.id_operacion AND ir_detalle_oper.cod_item=im_items.cod_item AND im_items.id_marca=ip_marcas.id_marca AND im_items.modelo=ip_modelos.id_modelo AND ir_operaciones.id_suc_cliente=nm_sucursal.id_sucursal AND ir_detalle_oper.modo_import=cp_tipo_importacion.id_tipotrans ");


